M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat Jun 20 19:09:22 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-20T19:09:22+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X104.0Y-54.0
X104.0Y-146.0
X196.0Y-54.0
X196.0Y-146.0
T0
M30
