[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wall
lib_deps =
    esphome/ESP32-audioI2S @ ^2.3.0
    bblanchon/ArduinoJson @ ^7.0.0
